def fib(a):
    if a<=1:
        return 0
    if a==2:
        return 1
    return fib(a-1)+fib(a-2)
def sum(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b